services:
  chromadb:
    image: ghcr.io/chroma-core/chroma:0.5.21
    container_name: chromadb
    ports:
      - "8000:8000"
    environment:
      # Tell Chroma to persist into /chroma/chroma
      - PERSIST_DIRECTORY=/chroma/chroma
      - IS_PERSISTENT=TRUE
    volumes:
      # Primary data store
      - chroma_data:/chroma/chroma

  backup:
    image: amazon/aws-cli:latest
    container_name: chroma_backup
    depends_on:
      - chromadb
    restart: always
    environment:
      # Provide your AWS credentials & bucket name via env_file or secrets
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - S3_BUCKET=${S3_BUCKET}      # e.g. my-org-chroma-backups
    volumes:
      # Mount the live data read‑only
      - chroma_data:/data:ro
      # Local snapshot store
      - chroma_backups:/backups
    entrypoint: >
      sh -c "
        # every 24h: snapshot + sync to S3
        while true; do
          TS=$(date +%F_%H%M)
          echo \"[Backup] snapshot at \$TS\"
          mkdir -p /backups/\$TS
          cp -r /data/* /backups/\$TS/
          echo \"[Backup] syncing /backups to s3://\$S3_BUCKET/\"
          aws s3 sync /backups s3://\$S3_BUCKET/ --delete
          sleep 86400
        done
      "

volumes:
  chroma_data:
    driver: local

  chroma_backups:
    driver: local
