services:
  chromadb:
    image: ghcr.io/chroma-core/chroma:0.5.21
    container_name: chromadb
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      PERSIST_DIRECTORY: /chroma/chroma
      IS_PERSISTENT: "TRUE"
    volumes:
      - chroma_data:/chroma/chroma

volumes:
  chroma_data:
    driver: local
